server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 认证服务路由 - auth-service使用/api/v1/auth路径
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        
        # 笔记服务路由 - note-service使用/api/notes路径
        - id: note-service
          uri: lb://note-service
          predicates:
            - Path=/api/notes/**

        # 点赞服务路由 - like-service使用/api/likes路径
        - id: like-service
          uri: lb://like-service
          predicates:
            - Path=/api/likes/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    appname: ${spring.application.name}


# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO 